---
- name: Gather facts
  setup:
  when: ansible_facts == {}

- name: Install Docker and Git on Amazon Linux
  block:
    - name: Install Docker via amazon-linux-extras
      command: amazon-linux-extras install -y docker
      register: docker_install
      changed_when: "'Nothing to do' not in docker_install.stdout"
      
    - name: Install Git
      yum:
        name: git
        state: present
  when: ansible_distribution == "Amazon"

- name: Install Docker and Git on other systems
  block:
    - name: Install Docker and Git on RedHat family
      yum:
        name:
          - docker
          - git
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: Install Docker and Git on Debian family
      apt:
        name:
          - docker.io
          - git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
  when: ansible_distribution != "Amazon"

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Check if Jenkins container is running
  command: docker ps -f name=jenkins
  register: jenkins_check
  changed_when: false

- name: Run Jenkins container
  command: docker run -d --name jenkins -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
  when: "'jenkins' not in jenkins_check.stdout"