---
- name: Gather facts
  setup:
  
- name: Install Docker on Amazon Linux
  command: amazon-linux-extras install -y docker
  when: ansible_distribution == "Amazon"
  register: docker_install_amazon
  changed_when: docker_install_amazon.rc == 0 and "Installing" in docker_install_amazon.stdout
  become: true

- name: Install Docker on CentOS/RHEL
  yum:
    name: docker
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"
  become: true

- name: Install Docker on Debian/Ubuntu
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

# Remove existing container to avoid conflicts
- name: Remove existing Nexus container if any
  shell: docker rm -f nexus || true
  become: true

# Create systemd service file for Nexus container
- name: Create Nexus systemd service
  copy:
    dest: /etc/systemd/system/nexus-container.service
    content: |
      [Unit]
      Description=Nexus Container
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker stop nexus
      ExecStartPre=-/usr/bin/docker rm nexus
      ExecStartPre=/usr/bin/docker pull sonatype/nexus3:latest
      ExecStart=/usr/bin/docker run --rm --name nexus -p 8081:8081 sonatype/nexus3:latest
      ExecStop=/usr/bin/docker stop nexus

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  become: true

# Reload systemd and start service
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Enable and start Nexus service
  systemd:
    name: nexus-container
    state: started
    enabled: yes
  become: true

# Verify service is accessible
- name: Wait for Nexus to be accessible
  uri:
    url: http://localhost:8081
    status_code: 200
  register: nexus_result
  until: nexus_result.status == 200
  retries: 10
  delay: 30
  ignore_errors: true
  become: true
...