---
- name: Gather facts
  setup:
  
- name: Install Docker on Amazon Linux
  command: amazon-linux-extras install -y docker
  when: ansible_distribution == "Amazon"
  register: docker_install_amazon
  changed_when: docker_install_amazon.rc == 0 and "Installing" in docker_install_amazon.stdout
  become: true

- name: Install Docker on CentOS/RHEL
  yum:
    name: docker
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"
  become: true

- name: Install Docker on Debian/Ubuntu
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Check if SonarQube container exists
  command: docker ps -a --filter "name=sonarqube" --format "{{.Names}}"
  register: sonarqube_container
  changed_when: false
  become: true

- name: Pull SonarQube image
  command: docker pull sonarqube:latest
  when: sonarqube_container.stdout != "sonarqube"
  become: true

- name: Run SonarQube container
  command: docker run -d --name sonarqube -p 9000:9000 --restart always sonarqube:latest
  when: sonarqube_container.stdout != "sonarqube"
  become: true