---
- name: Gather facts
  setup:
  
- name: Install Docker on Amazon Linux
  command: amazon-linux-extras install -y docker
  when: ansible_distribution == "Amazon"
  register: docker_install_amazon
  changed_when: docker_install_amazon.rc == 0 and "Installing" in docker_install_amazon.stdout
  become: true

- name: Install Docker on CentOS/RHEL
  yum:
    name: docker
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"
  become: true

- name: Install Docker on Debian/Ubuntu
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

# Remove existing container to avoid conflicts
- name: Remove existing SonarQube container if any
  shell: docker rm -f sonarqube || true
  become: true

# Create systemd service file for SonarQube container
- name: Create SonarQube systemd service
  copy:
    dest: /etc/systemd/system/sonarqube-container.service
    content: |
      [Unit]
      Description=SonarQube Container
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker stop sonarqube
      ExecStartPre=-/usr/bin/docker rm sonarqube
      ExecStartPre=/usr/bin/docker pull sonarqube:latest
      ExecStart=/usr/bin/docker run --rm --name sonarqube -p 9000:9000 sonarqube:latest
      ExecStop=/usr/bin/docker stop sonarqube

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  become: true

# Reload systemd and start service
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true

- name: Enable and start SonarQube service
  systemd:
    name: sonarqube-container
    state: started
    enabled: yes
  become: true

# Verify service is accessible
- name: Wait for SonarQube to be accessible
  uri:
    url: http://localhost:9000
    status_code: 200
  register: sonarqube_result
  until: sonarqube_result.status == 200
  retries: 10
  delay: 30
  ignore_errors: true
  become: true
...